version: '3'
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-app
    networks:
      - luis
    ports:
      - 3000:3000
    container_name: next-app
    restart: always
networks:
  luis:
    external: true
