name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker stop next-app && docker rm next-app
    - name: Remove existing image
      run: docker image rm next-app
    - name: Build Docker image
      run: docker build -t next-app .
    - name: Run Docker container
      run: docker run -d --name next-app --net=my-net -p 3000:3000 next-app