name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: docker stop next-app && docker rm next-app

      - name: Remove existing image
        run: docker image rm next-app

      - name: Build Docker image
        run: docker build -t next-app .

      - name: Run Docker container
        run: docker run -d --name next-app --net=my-net -p 3000:3000 next-app
